Разбираю основы библиотеки numpy

In [1]:
import numpy as np

In [3]:
data = [1, 2, 3, 4, 5]

arr = np.array(data)

print(arr) # отображаем массив 
print(arr.shape) # отображаем количество элементов массива
print(arr.dtype) #отображаем тип данных массива
print(arr.ndim) # отображаем размерность данных (1D)

[1 2 3 4 5]
(5,)
int32
1


In [6]:
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2) # отображаем массив 
print(arr2.shape) # отображаем количество элементов массива
print(arr2.dtype) #отображаем тип данных массива
print(arr2.ndim) # отображаем размерность данных (1D)

[1 2 3 4 5]
(5,)
int32
1


In [15]:
# dtype=np.float устарело, теперь просто dtype=float
arr3 = np.array([1, 2, 3, 4, 5], dtype=float)
print(arr3) # отображаем массив 
print(arr3.shape) # отображаем количество элементов каждой размерности, в данном случае размерность 1D
print(arr3.dtype) #отображаем тип данных массива
print(arr3.ndim) # отображаем размерность данных (1D)
print(len(arr3)) # длина вектора (кол-во ячеек)
print(arr3.size) # размер вектора (массива)

[1. 2. 3. 4. 5.]
(5,)
float64
1
5
5


In [20]:
arr3 = arr3.astype(np.int64) # метод, приводящий элементы arr3 в другой тип данных
print(arr3)
print(arr3.dtype)

[1 2 3 4 5]
int64


In [21]:
arr4 = np.arange(0,20,1.5) # функция генерации вектора, от 0 до 20 с шагом 1.5

arr4

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5])

In [22]:
arr5 = np.linspace(0,2,5) # получить 5 чисел от 0 до 2

arr5

array([0. , 0.5, 1. , 1.5, 2. ])

In [24]:
arr5 = np.linspace(0,2,50) # получить 50 чисел от 0 до 2

arr5

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

In [25]:
random_arr = np.random.random((5,)) # получить вектор из 5 рандомных чисел (видимо по умолчанию от 0 до 1)

random_arr

array([0.92075303, 0.82574297, 0.18761833, 0.87686639, 0.39759287])

In [28]:
random_arr2 = np.random.random_sample((5,)) # работает примерно таким же образом, позволяетполучить вектор из 5 рандомных чисел (видимо по умолчанию от 0 до 1)

random_arr2

array([0.15236994, 0.03191157, 0.69462633, 0.30914992, 0.26266892])

Диапазон случайных чисел от [a,b]: (b-a)*np.random() + a, где b>a

In [34]:
# 5 случайных значений от -5 до 10
random_arr3 = (10 - -5) * np.random.random_sample((5,)) - 5

random_arr3

array([ 4.48956564,  0.73835801,  7.96926301,  9.6316714 , -2.93084345])

In [66]:
# 5 случайных значений от 2 до 15 (не включая 15) + перевод в int
random_arr3 = (15 - 2) * np.random.random_sample((5,)) + 2
random_arr3 = random_arr3.astype(np.int64)
random_arr3

array([ 5, 12, 13,  2, 10], dtype=int64)

Операции

In [69]:
arr = np.array([1, 2, 3, 4, 5])

arr = np.sqrt(arr)
print(arr)

arr = np.sin(arr)
print(arr)

arr = np.cos(arr)
print(arr)

arr = np.log(arr)
print(arr)

arr = np.exp(arr)
print(arr)

[1.         1.41421356 1.73205081 2.         2.23606798]
[0.84147098 0.98776595 0.98702664 0.90929743 0.78674913]
[0.66636675 0.55055622 0.55117323 0.61430028 0.70615086]
[-0.40591509 -0.59682621 -0.59570612 -0.48727141 -0.34792639]
[0.66636675 0.55055622 0.55117323 0.61430028 0.70615086]


In [74]:
# сложение матриц
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

c = a + b
print(c)
# либо с помощью другой функции
c = np.add(a,b)
print(c)


[ 7  9 11 13 15]
[ 7  9 11 13 15]


In [78]:
# умножение
c = a * b
print(c)
c = np.multiply(a,b)
print(c)

[ 6 14 24 36 50]
[ 6 14 24 36 50]


In [83]:
# вычитание
c = a - b
print(c)
c = np.subtract(a,b)
print(c)

[-5 -5 -5 -5 -5]
[-5 -5 -5 -5 -5]


In [84]:
# деление
c = a / b
print(c)
c = np.divide(a,b)
print(c)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [95]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr * 2 # все элементы вектора arr умножить на 2
print(arr)

[ 2  4  6  8 10]


In [96]:
arr = arr ** 2 # все элементы вектора arr возвести в степень 2
arr

array([  4,  16,  36,  64, 100])

In [86]:
# умножение массива на 2 без использования numpy приводит к дублированию массива
simple_list = [1, 2, 3, 4, 5]
simple_list = simple_list *2
print(simple_list)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


Функции агрегаты

In [106]:
arr = np.random.randint(-5, 10, 10) # сформировать вектор из 10 целых чисел, от -5 до 10
arr

array([ 3,  8, -2,  7,  4, -5,  0,  1,  4, -2])

In [101]:
print(arr.max())
print(arr.min())
print(arr.mean())
print(arr.sum())
print(arr.std())
print(np.median(arr))

9
-2
1.7
17
2.934280150224242
1.0


In [111]:
arr < 2 # логическое сравнение всего массива

array([False, False,  True, False, False,  True,  True,  True, False,
        True])

Манипуляции с массивами

In [114]:
np.insert(arr,2,-20) # вставляем значение -20 в ячейку 2 массива arr

array([  3,   8, -20,  -2,   7,   4,  -5,   0,   1,   4,  -2])

In [115]:
np.delete(arr, 2) # удаляем элемент из 2 ячейки в массиве arr

array([ 3,  8,  7,  4, -5,  0,  1,  4, -2])

In [116]:
np.sort(arr) # сортировка по умолчанию по возрастанию

array([-5, -2, -2,  0,  1,  3,  4,  4,  7,  8])

In [118]:
arr2 = np.array([0, 0, 0])
arr = np.concatenate((arr, arr2))
arr

array([ 3,  8, -2,  7,  4, -5,  0,  1,  4, -2,  0,  0,  0,  0,  0,  0])

In [ ]:
print("KEK")